import type { ExpenseCategory } from "./types";

export const CATEGORY_KEYWORDS: Record<ExpenseCategory, string[]> = {
  transport: [
    "uber",
    "lyft",
    "taxi",
    "train",
    "rail",
    "flight",
    "airport",
    "metro",
    "bus",
    "tram",
  ],
  food: ["restaurant", "cafe", "coffee", "lunch", "dinner", "breakfast", "bar", "bistro"],
  accommodation: ["hotel", "hostel", "booking", "airbnb", "resort", "check-in"],
  fuel: ["fuel", "petrol", "diesel", "gas station", "shell", "bp", "totalenergies"],
  parking: ["parking", "garage", "meter", "park ticket"],
  telecom: ["telecom", "mobile", "sim", "data plan", "internet", "wifi"],
  office_supplies: ["office depot", "staples", "stationery", "printer", "paper", "ink"],
  entertainment: ["cinema", "movie", "concert", "event", "museum"],
  other: [],
};

export const VENDOR_HINTS: Record<string, ExpenseCategory> = {
  uber: "transport",
  lyft: "transport",
  bolt: "transport",
  marriott: "accommodation",
  hilton: "accommodation",
  ibis: "accommodation",
  shell: "fuel",
  bp: "fuel",
  starbucks: "food",
  mcdonald: "food",
  subway: "food",
  verizon: "telecom",
  vodafone: "telecom",
  staples: "office_supplies",
};

export const CITY_TO_COUNTRY: Record<string, string> = {
  "new york": "US",
  chicago: "US",
  boston: "US",
  austin: "US",
  miami: "US",
  london: "GB",
  manchester: "GB",
  paris: "FR",
  lyon: "FR",
  berlin: "DE",
  munich: "DE",
  madrid: "ES",
  barcelona: "ES",
  rome: "IT",
  milan: "IT",
  brussels: "BE",
  amsterdam: "NL",
  lisbon: "PT",
  zurich: "CH",
  vienna: "AT",
  dubai: "AE",
  singapore: "SG",
  tokyo: "JP",
  osaka: "JP",
  sydney: "AU",
  melbourne: "AU",
  toronto: "CA",
  vancouver: "CA",
};

export const CATEGORY_ORDER: ExpenseCategory[] = [
  "transport",
  "food",
  "accommodation",
  "fuel",
  "parking",
  "telecom",
  "office_supplies",
  "entertainment",
  "other",
];

